// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI8x-BZfGJZBRbM73-FoRAmapnPw-qlmg',
    appId: '1:760251999490:web:c27c159fbd1130d11bce1b',
    messagingSenderId: '760251999490',
    projectId: 'picapool-2ead6',
    authDomain: 'picapool-2ead6.firebaseapp.com',
    storageBucket: 'picapool-2ead6.appspot.com',
    measurementId: 'G-J3MQ7CZEWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoAHaJWyiCrTL4UnoE0I7jEpYja872Psk',
    appId: '1:760251999490:android:53673c6a16216a111bce1b',
    messagingSenderId: '760251999490',
    projectId: 'picapool-2ead6',
    storageBucket: 'picapool-2ead6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOmVqt1P52vfGKoiFnc6jlUSdceymz-k',
    appId: '1:760251999490:ios:bef6698bfdf0d0b61bce1b',
    messagingSenderId: '760251999490',
    projectId: 'picapool-2ead6',
    storageBucket: 'picapool-2ead6.appspot.com',
    iosClientId:
        '760251999490-d9tdpimki92q54206q10daco3fahn4vi.apps.googleusercontent.com',
    iosBundleId: 'com.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOmVqt1P52vfGKoiFnc6jlUSdceymz-k',
    appId: '1:760251999490:ios:785bf11df6bd62c01bce1b',
    messagingSenderId: '760251999490',
    projectId: 'picapool-2ead6',
    storageBucket: 'picapool-2ead6.appspot.com',
    iosClientId:
        '760251999490-fek95rnb0a0i5ljnb9hkthlb7ubbpdg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.picapool.RunnerTests',
  );
}
