name: Finally Releasing IPA

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods xcpretty
          pod repo update

      - name: Flutter clean
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Install iOS dependencies
        run: |
          cd ios
          cp Podfile.test Podfile
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      # ---------------- Signing Setup ----------------
      - name: Install Signing Assets
        run: |
          echo "Using local SigningAssets..."
          security create-keychain -p temp_pw signing.keychain
          security unlock-keychain -p temp_pw signing.keychain
          security import ios/SigningAssets/cert.p12 -k signing.keychain -P "dipan" -T /usr/bin/codesign
          security list-keychains -d user -s signing.keychain login.keychain

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios/SigningAssets/Picapool_AppStore_Profile.mobileprovision \
             ~/Library/MobileDevice/Provisioning\ Profiles/23ca837c-3da0-4490-89e1-e74de0f7d55a.mobileprovision
          echo "✅ P12 & mobileprovision installed."

      - name: Debug Signing Info
        run: |
          echo "=== Available Identities ==="
          security find-identity -v -p codesigning
          echo "=== Provisioning Profiles ==="
          ls -lh ~/Library/MobileDevice/Provisioning\ Profiles/

      # ---------------- Build IPA ----------------
      - name: Build IPA
        run: |
          echo "Building IPA..."
          flutter build ipa --release \
            --export-options-plist=ios/Runner/ExportOptions.plist

      - name: Show IPA
        run: |
          echo "=== IPA Files ==="
          ls -lh build/ios/ipa || echo "IPA not generated"
