name: Test iOS Build

on:
  push:
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'  # Change to your Flutter version

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Flutter clean
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS (No codesign)
        run: flutter build ios --no-codesign
